[package]
name = "ud_server"
version = "0.1.0"
edition = "2021"

[lib]
name = "ud_server"
path = "src/lib.rs"

[dependencies]
ud_link = { path = "../link" }
ud_ctrl = { path = "../ctrl" }
tokio = { version = "1.45.1", features = ["full"] }






