[package]
name = "ud_server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ud_server"
path = "src/main.rs"

[dependencies]
ud_link = { path = "../lib/all/link" }
ud_ctrl = { path = "../lib/all/ctrl" }
tokio = { version = "1.47.1", features = ["full"] }






