[package]
name = "ud_client"
version = "0.1.0"
edition = "2021"
[lib]
name = "ud_client"
path = "src/lib.rs"
[dependencies]

mdns-sd ="0.13.9"
tokio = { version = "1.45.1", features = ["full"] }
once_cell = "1.21.3"