import { Device } from "device_search.slint";
import { Button, StandardButton ,VerticalBox, ListView } from "std-widgets.slint";
export component AppWindow inherits Window {
    callback show-settings();

    in-out property <[Device]> name;
    background: gray; 
    Button {
        text: "Search for devices";
        clicked => {
            root.show-settings();
        }
    }
}

export component device_search inherits Dialog {
    
    in-out property <[Device]> devices_list;


    preferred-width: 800px;
    preferred-height: 600px;
    min-height: 600px;
    min-width: 300px;
    VerticalBox {
        ListView {
            for data in devices_list: Rectangle {
                preferred-height: 50px;
                preferred-width: 100%;
                Button {
                    width: 100%;
                    text: data.device_name + "                " + data.IP_address;
                    clicked => {}


                }
            }
        }
    }
}